menu:
  Home: /
  Archives: /archives
rss: /atom.xml
language: 
- zh-CN
- zh-TW
- default


friendship_chaining_site:
  塘主Levan: https://levanax.github.io/
  szpua: http://www.szpua.com

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

facebook:
google_plus:
twitter:
github: levanax

fancybox: true
google_analytics: