menu:
  Home: /
  Archives: /archives
rss: /atom.xml
language: 
- zh-CN

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

facebook:
google_plus:
twitter:
github: levanax

fancybox: true
google_analytics: